export const TypeofCollege = [
    { name: "Private", id: "0" },
    { name: "Government", id: "1" }
  ];
  export const TypeofCategory = [
    { name: "Week Hansa", id: "0" },
    { name: "Toi", id: "1" },
    { name: "Learnerhunt", id: "2" }

  ];

  // export const coursenameList = [
  //   { label: 'DE'},
  //   { label: 'D.Pharma'},
  //   { label: 'D.Language '},
  //   { label: 'DMLT'},
  //   { label: 'DPT'},
  //   { label: 'D.Law'},
  //   { label: 'D.Paramedical'},
  //   { label: 'D.Science'},
  //   { label: 'DHM'},
  //   { label: 'DMC'},
  //   { label: 'D.Design'},
  //   { label: 'D.El.Ed'},
  //   { label: 'DCA'},
  //   { label: 'D.Aviation'},
  //   { label: 'D.Dental'},
  //   { label: 'DVC'},
  //   { label: 'D.Arch'},
  //   { label: 'B.Tech'},
  //   { label: 'BE'},
  //   { label: 'BA'},
  //   { label: 'BA (Hons)'},
  //   { label: 'B.Sc'},
  //   { label: 'B.Sc (Hons)'},
  //   { label: 'BBA'},
  //   { label: 'BTTM'},
  //   { label: 'B.Com'},
  //   { label: 'B.Com (Hons)'},
  //   { label: 'B.Ed'},
  //   { label: 'BCA'},
  //   { label: 'B.Des'},
  //   { label: 'BA (JMC)'},
  //   { label: 'BFA'},
  //   { label: 'B.VSc'},
  //   { label: 'B.Pharma'},
  //   { label: 'BDS'},
  //   { label: 'B.Arch'},
  //   { label: 'B.Plan'},
  //   { label: 'B.Voc'},
  //   { label: 'MBBS'},
  //   { label: 'BUMS'},
  //   { label: 'BAMS'},
  //   { label: 'LLB'},
  //   { label: 'PBBS'},
  //   { label: 'PGD'},
  //   { label: 'MBA'},
  //   { label: 'M.Tech'},
  //   { label: 'ME'},
  //   { label: 'MS'},
  //   { label: 'M.Sc'},
  //   { label: 'MA'},
  //   { label: 'M.Com'},
  //   { label: 'MDS'},
  //   { label: 'M.Pharma'},
  //   { label: 'M.VSc'},
  //   { label: 'MJMC'},
  //   { label: 'M.Text'},
  //   { label: 'M.Des'},
  //   { label: 'M.F.Tech'},
  //   { label: 'M.Plan'},
  //   { label: 'M.Arch'},
  //   { label: 'MTHM'},
  //   { label: 'M.Ed'},
  //   { label: 'M.P.Ed'},
  //   { label: 'MCA'},
  //   { label: 'LLM'},
  //   { label: 'M.Phil'},
  //   { label: 'MD'},
  //   { label: 'LLD'},
  //   { label: 'Ph.D.'}
  // ];

  export const coursenameList = [
    { label: 'DE', fullName: 'Diploma in Engineering' },
    { label: 'D.Pharma', fullName: 'Diploma in Pharmacy' },
    { label: 'D.Language', fullName: 'Diploma in Foreign Languages' },
    { label: 'DMLT', fullName: 'Diploma in Medical Laboratory Technology' },
    { label: 'DPT', fullName: 'Diploma in Physiotherapy' },
    { label: 'D.Law', fullName: 'Diploma in Law' },
    { label: 'D.Paramedical', fullName: 'Diploma in Paramedical Sciences' },
    { label: 'D.Science', fullName: 'Diploma in Science' },
    { label: 'DHM', fullName: 'Diploma in Hotel Management' },
    { label: 'DMC', fullName: 'Diploma in Mass Communication' },
    { label: 'D.Design', fullName: 'Diploma in Design' },
    { label: 'D.El.Ed', fullName: 'Diploma in Elementary Education' },
    { label: 'DCA', fullName: 'Diploma in Computer Applications' },
    { label: 'D.Aviation', fullName: 'Diploma in Aviation' },
    { label: 'D.Dental', fullName: 'Diploma in Dental Science' },
    { label: 'DVC', fullName: 'Diploma in Visual Communication' },
    { label: 'D.Arch', fullName: 'Diploma in Architecture' },
    { label: 'B.Tech', fullName: 'Bachelor of Technology' },
    { label: 'BE', fullName: 'Bachelor of Engineering' },
    { label: 'BA', fullName: 'Bachelor of Arts' },
    { label: 'BA (Hons)', fullName: 'Bachelor of Arts (Honours)' },
    { label: 'B.Sc', fullName: 'Bachelor of Science' },
    { label: 'B.Sc (Hons)', fullName: 'Bachelor of Science (Honours)' },
    { label: 'BBA', fullName: 'Bachelor of Business Administration' },
    { label: 'BTTM', fullName: 'Bachelor of Travel and Tourism Management' },
    { label: 'B.Com', fullName: 'Bachelor of Commerce' },
    { label: 'B.Com (Hons)', fullName: 'Bachelor of Commerce (Honours)' },
    { label: 'B.Ed', fullName: 'Bachelor of Education' },
    { label: 'BCA', fullName: 'Bachelor of Computer Applications' },
    { label: 'B.Des', fullName: 'Bachelor of Design' },
    { label: 'BA (JMC)', fullName: 'Bachelor of Arts in Journalism and Mass Communication' },
    { label: 'BFA', fullName: 'Bachelor of Fine Arts' },
    { label: 'B.VSc', fullName: 'Bachelor of Veterinary Science' },
    { label: 'B.Pharma', fullName: 'Bachelor of Pharmacy' },
    { label: 'BDS', fullName: 'Bachelor of Dental Surgery' },
    { label: 'B.Arch', fullName: 'Bachelor of Architecture' },
    { label: 'B.Plan', fullName: 'Bachelor of Planning' },
    { label: 'B.Voc', fullName: 'Bachelor of Vocation' },
    { label: 'MBBS', fullName: 'Bachelor of Medicine, Bachelor of Surgery' },
    { label: 'BUMS', fullName: 'Bachelor of Unani Medicine and Surgery' },
    { label: 'BAMS', fullName: 'Bachelor of Ayurvedic Medicine and Surgery' },
    { label: 'LLB', fullName: 'Bachelor of Laws' },
    { label: 'PBBS', fullName: 'Post Basic B.Sc Nursing' },
    { label: 'PGD', fullName: 'Post Graduate Diploma' },
    { label: 'MBA', fullName: 'Master of Business Administration' },
    { label: 'M.Tech', fullName: 'Master of Technology' },
    { label: 'ME', fullName: 'Master of Engineering' },
    { label: 'MS', fullName: 'Master of Science' },
    { label: 'M.Sc', fullName: 'Master of Science' },
    { label: 'MA', fullName: 'Master of Arts' },
    { label: 'M.Com', fullName: 'Master of Commerce' },
    { label: 'MDS', fullName: 'Master of Dental Surgery' },
    { label: 'M.Pharma', fullName: 'Master of Pharmacy' },
    { label: 'M.VSc', fullName: 'Master of Veterinary Science' },
    { label: 'MJMC', fullName: 'Master of Journalism and Mass Communication' },
    { label: 'M.Text', fullName: 'Master of Textiles' },
    { label: 'M.Des', fullName: 'Master of Design' },
    { label: 'M.F.Tech', fullName: 'Master of Fashion Technology' },
    { label: 'M.Plan', fullName: 'Master of Planning' },
    { label: 'M.Arch', fullName: 'Master of Architecture' },
    { label: 'MTHM', fullName: 'Master of Tourism and Hotel Management' },
    { label: 'M.Ed', fullName: 'Master of Education' },
    { label: 'M.P.Ed', fullName: 'Master of Physical Education' },
    { label: 'MCA', fullName: 'Master of Computer Applications' },
    { label: 'LLM', fullName: 'Master of Laws' },
    { label: 'M.Phil', fullName: 'Master of Philosophy' },
    { label: 'MD', fullName: 'Doctor of Medicine' },
    { label: 'LLD', fullName: 'Doctor of Laws' },
    { label: 'Ph.D.', fullName: 'Doctor of Philosophy' }
];

  export const courseeligibiltyCriteria = [
    { label: '40'},
    { label: '50'},
    { label: '60'},
    { label: '70'},
    { label: '80'},
    { label: '90'},
    { label: 'other'},
  ];  

  export const coursefulleligibiltyCriteria = [
    { label: 'Candidates must have passed the 12th standard examination with at least 50% aggregate for general category and 45% aggregate for reserved category candidates.'},
    { label: 'Candidates must have a bachelors degree in any discipline with at least 50% aggregate for general category and 45% aggregate for reserved category candidates.'},
    { label: 'Candidates must have a bachelors degree in any discipline with at least 50% aggregate forgeneral category and 45% aggregate for reserved category candidates with minimum 2-3years work experiance.'},
    { label: 'Candidates must have a masters degree in any discipline with at least 55% aggregate for general category and 50% aggregate for reserved category candidates.'},
    
  ];  
  export const coursestudymode = [
    { label: 'Executive Studies'},
    { label: 'Distance Learning'},
    { label: 'Full Time '},
    { label: 'Part Time '}
  ];
  export const courseduration = [
    { label: '1 Year'},
    { label: '2 Year'},
    { label: '3 Year'},
    { label: '4 Year'},
    { label: '5 Year'}
  ];